### ISSUE TITLE
Cannot run program "7za"

### ISSUE THREAD

**Issue by a154225859** [zouyuanfeng/AndResGuardDemo#1]
java.io.IOException: Cannot run program "7za": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:620)
        at java.lang.Runtime.exec(Runtime.java:450)
        at java.lang.Runtime.exec(Runtime.java:347)
        at com.tencent.mm.androlib.ResourceApkBuilder.generalRaw7zip(ResourceApkBuilder.java:268)
        at com.tencent.mm.androlib.ResourceApkBuilder.use7zApk(ResourceApkBuilder.java:77)
        at com.tencent.mm.androlib.ResourceApkBuilder.buildApk(ResourceApkBuilder.java:47)
        at com.tencent.mm.resourceproguard.Main.buildApk(Main.java:93)
        at com.tencent.mm.resourceproguard.Main.resourceProguard(Main.java:70)
        at com.tencent.mm.resourceproguard.cli.CliMain.run(CliMain.java:192)
        at com.tencent.mm.resourceproguard.cli.CliMain.main(CliMain.java:36)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 10 more

**Comment by zouyuanfeng** [comment]
see：http://blog.csdn.net/u014300915/article/details/50601940
在首页上已添加，解决方法
